### PR TITLE
fix: fix Android Build

### LINKED ISSUE #60: [v 4.0.0] Android app doesn't compile because an error: Cannot set the value of property ‘id’ of type java.lang.String using an instance of type org.apache.groovy.json.internal.LazyMap
By Creating a brand new React Native project and following all installation steps as described  [In the documentation](https://github.com/onfido/react-native-sdk#4-adding-the-onfido-react-native-sdk-to-your-project), the application will not compile because of this error that is located in the `gradle.publish` file:

`Cannot set the value of property ‘id’ of type java.lang.String using an instance of type org.apache.groovy.json.internal.LazyMap`

Configuration:
- onfido sdk version: 4.0.0
- gradle: 7.0.2
- react-native version: 0.65.1
- buildToolsVersion: "30.0.2"
- minSdkVersion: 21
- compileSdkVersion: 31
- targetSdkVersion: 30
- ndkVersion: "21.4.7075529"

steps to reproduce:

- `create-react-native-app my-project`
- `cd my-project`
-  `npm install @onfido/react-native-sdk --save`
- `npm --prefix node_modules/@onfido/react-native-sdk/ run updateBuildGradle`
- `npm run android`

I perform these steps also in an existing project getting the same error.

### PR DESCRIPTION
**Pull request by andreaSimonePorceddu**
It fixes [this issue](https://github.com/onfido/react-native-sdk/issues/60)

Closes #60

### CODE REVIEW

**Comment by R4md4c** [comment]
Thanks for your contribution, the changes LGTM, and makes sense!

**Comment by andreaSimonePorceddu** [comment]
Hey @R4md4c, when this should be released?

**Comment by R4md4c** [comment]
Hey @andreaSimonePorceddu, we're investigating other issues happening in the RN SDK to see if they could make the next release or not, once these are sorted out, we will perform a release. 

Meanwhile you can keep using what's in master to not get blocked.

**Comment by R4md4c** [comment]
Hey @andreaSimonePorceddu, We've released this fix as part of v4.0.1, let us know please if something not right.

**Pull request merged**
