### PR TITLE
Typescript support

### LINKED ISSUE #1: Typescript support
Since react-native projects are becoming mostly written in Typescript, we need this support

### PR DESCRIPTION
**Pull request by AndreiBehel**
Closes #1

### CODE REVIEW

**Review by FDiskas — APPROVED** [review]

**Comment by DominicTobias** [comment]
Any movement on this? 🥲

**Comment by fritsFigo** [comment]
Would be nice if this MR could me merged!

**Comment by FDiskas** [comment]
Huston - we have conflicts here. Not a big deal but. Please update your branch.

**Comment by PedrinhoDS** [comment]
Closing this MR, as the package now supports Typescript.

**Pull request closed without merging**
